CourseProject1
belousoveu/courseproject1 pull request #1
Opened 2024-07-04 17:33 UTC by belousoveu

2024-07-05 16:26 UTC, OlgaLugacheva requested changes

2024-07-05 16:26 UTC, OlgaLugacheva commented on src/Employee.java
> +    private int employeeId;
поле лучше так и оставить id - из названия класса ясно, к чему оно относится

2024-07-05 16:26 UTC, OlgaLugacheva commented on src/EmployeeBook.java
> +            if (employees[i] == null || employees[i].getId() == 0) {
не совсем понятно, чем id = 0 неугоден
понятно, что в конструкторе невозможно установить 0, но все же выглядит избыточно

2024-07-05 16:26 UTC, OlgaLugacheva commented on src/EmployeeBook.java
> +        return null;
на будущее : стоит избегать методов , возращающих null
раз уже есть понимание исключений - то лучше бросить исключение

2024-07-05 16:26 UTC, OlgaLugacheva commented on src/EmployeeBook.java
> +            throw new RuntimeException(e);
тут было бы в данном контексте лучше сообщить пользователю в консоль , о том что "Не получилось сохранить"
так как  без обработчика конслоьное приложение просто завершит работу, что не очень-то хорошо

2024-07-05 16:26 UTC, OlgaLugacheva commented on src/EmployeeBook.java
> +            throw new RuntimeException(e);
тут аналогично, ну можно было придумать, что если не получилось считать из файла, то введи , дорогой пользователь, данные руками

2024-07-06 12:17 UTC, belousoveu commented on src/Employee.java
> +    private int employeeId;
Исправил. Смутило изначально, что при сдаче ДЗ всегда требовали именовать переменные максимально полно.

2024-07-06 12:18 UTC, belousoveu commented on src/EmployeeBook.java
> +            if (employees[i] == null || employees[i].getId() == 0) {
Согласен, что условие избыточное. Привычка - лучше написать избыточное условие, чем потом разбираться почему вдруг неправильно работает :)
Поправил.

2024-07-06 12:19 UTC, belousoveu commented on src/EmployeeBook.java
> +        return null;
Принял. Переписал все методы, которые возвращали null. Обработал исключения в вызывающих методах.

2024-07-06 12:20 UTC, belousoveu commented on src/EmployeeBook.java
> +            throw new RuntimeException(e);
Аналогично предыдущему
Исправил. Убрал вызов исключения. Оставил  только сообщение пользователю об ошибке.

2024-07-11 15:49 UTC, merged